import Head from 'next/head';
import Hero from '@/components/Hero';
import { apparel } from '@/shared/variables/hero';

export default function Home() {
  const { title, subtitle, image } = apparel;
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero title={title} subtitle={subtitle} image={image} />
    </>
  );
}
